spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bmap?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&autoReconnection=true&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: bmap
    password: bmap


  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  sql:
    init:
      mode: never
      #schema-locations: classpath:sql/schema.sql
      #data-locations: classpath:sql/data.sql

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

api:
  serviceKey: 123
  type: 123
  numOfRows: 123

